#!/usr/bin/env bash
set -eu -o pipefail
dr=${DOCKER_REGISTRY:-benwbooth}
img=${DOCKER_IMAGE:-$(basename "$(cd "$(dirname "$0")" && pwd)")}
docker build -t "$dr/$img" "$@" -- "$(dirname "$0")"
docker push "$dr/$img"
read -p 'Enter VPN username: ' vpnuser
read -s -p 'Enter VPN password: ' vpnpass
echo
kubectl create secret generic vpn-login --from-literal=USER="$vpnuser" --from-literal=PASSWORD="$vpnpass"
